name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '16'
          cache: 'yarn'

      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
